
ProbStatBook.pdf:  ProbStatBook.tex \
                   Includes/Includes.tex Cover.tex \
                   Preface.tex DiscreteProb.tex ContinProb.tex ProbCalc.tex \
		   MultVarDistr.tex RandVecs.tex ConfInts.tex \
		   LinReg.tex \
		   Class.tex NormalFamily.tex \
		   RandVecs.tex StopAndReview.tex \
		   DisMarkovIntro.tex ExponDistr.tex PauseToReflect.tex \
		   Intro.tex StatPrologue.tex \
		   AuthorBio.tex \
		   GGPlot2Intro.tex DiscreteParFams.tex \
		   MatrixReview.tex \
		   R5MinIntro.tex
	pdflatex ProbStatBook.tex

